/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kelly_jnitest_HiJni */

#ifndef _Included_com_kelly_jnitest_HiJni
#define _Included_com_kelly_jnitest_HiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kelly_jnitest_HiJni
 * Method:    cCallJava1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelly_jnitest_HiJni_cCallJava1
  (JNIEnv *, jobject);

/*
 * Class:     com_kelly_jnitest_HiJni
 * Method:    cCallJava2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelly_jnitest_HiJni_cCallJava2
  (JNIEnv *, jobject);

/*
 * Class:     com_kelly_jnitest_HiJni
 * Method:    cCallJava3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kelly_jnitest_HiJni_cCallJava3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
