/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kelly_jnitest_HelloJni */

#ifndef _Included_com_kelly_jnitest_HelloJni
#define _Included_com_kelly_jnitest_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kelly_jnitest_HelloJni
 * Method:    javaCallCToAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kelly_jnitest_HelloJni_javaCallCToAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kelly_jnitest_HelloJni
 * Method:    javaCallCToPrint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kelly_jnitest_HelloJni_javaCallCToPrint
  (JNIEnv *, jobject , jstring);

/*
 * Class:     com_kelly_jnitest_HelloJni
 * Method:    javaCallCToHandleArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_kelly_jnitest_HelloJni_javaCallCToHandleArray
  (JNIEnv *, jobject, jintArray);


#ifdef __cplusplus
}
#endif
#endif
